bestclick:
  logging:
    exception:
      business: true
      server: true


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/core
    username: core
    password: "0000"
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false

logging:
  level:
    sql: debug